version: 1.0.{build}
image: Ubuntu1804  # образ для сборки
environment:
  GITHUB_TOKEN: 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
build: off
stack: node 17  # окружение
branches:
  only:
    - master  # ветка git
cache: node_modules  # кеширование
install:
  - npm install  # команда установки зависимостей
test_script:
  - npm run lint && npm test  # скрипт тестирования

