version: 1.0.{build}
image: Visual Studio 2019
environment:
  GITHUB_TOKEN: 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
build:
  verbosity: minimal
stack: node 17  # окружение
branches:
  only:
    - master  # ветка git
cache: node_modules  # кеширование
install:
  - npm install  # команда установки зависимостей
test_script:
  - npm run lint && npm test  # скрипт тестирования